import { type ICON_NAME } from '@ovhcloud/ods-react-icon/src';

type IconNameKey = keyof typeof ICON_NAME;

/**
 * Try to keep the tags meaningful, they should represent possible search value from a user or an alternative name
 * (ex: "day" for "calendar" or "times" for "xmark")
 * Do not add tag copying part of the icon name, as the search will find them anyway
 * (ex: do not add "arrow" tag to "arrowCrossed" icon)
 * Not every icon needs to have tags, add them only if relevant
 * Keep each tag list small (ideally no more than 4 elements)
 * Keep the tag high-level, it does not describe the state represented on the icon
 * (ex: do not add "lab-full" tag to "flask-full" icon, just add "lab" on each flask icon)
 */
const ODS_ICON_TAG: { [NameKey in IconNameKey]: string[] } = {
  accessibility: ['universal access', 'a11y'],
  accessibilityFull: ['universal access', 'a11y'],
  analysis: ['data', 'graph', 'metrics'],
  arrowCrossed: ['branch', 'git'],
  arrowDown: [],
  arrowDownLeft: [],
  arrowDownRight: [],
  arrowLeft: ['back', 'previous'],
  arrowLeftRight: ['swap', 'exchange'],
  arrowRight: ['forward', 'next'],
  arrowUp: [],
  arrowUpDown: ['swap', 'reorder'],
  arrowUpLeft: [],
  arrowUpRight: [],
  bell: ['notification', 'alert'],
  bill: ['invoice', 'receipt'],
  blog: [],
  book: ['read', 'guide'],
  box: ['pack', 'storage', 'delivery', 'parcel'],
  brain: ['intelligence', 'knowledge', 'thinking'],
  building: ['company', 'facility', 'office'],
  cable: ['connect', 'wire', 'link'],
  calculator: ['maths', 'total', 'convert'],
  calendar: ['day', 'month', 'year', 'schedule', 'date', 'event'],
  castle: ['fortress', 'protection', 'security'],
  chainLink: [],
  check: ['validation', 'verified', 'approved', 'success'],
  chevronDoubleLeft: ['forward', 'next'],
  chevronDoubleRight: ['back', 'previous'],
  chevronDown: ['expand', 'collapse'],
  chevronLeft: ['back', 'previous'],
  chevronLeftSlash: ['code', 'html', 'tags'],
  chevronLeftUnderscore: ['code', 'terminal'],
  chevronRight: ['forward', 'next'],
  chevronUp: ['close, collapse'],
  circleCheck: ['validation', 'verified', 'approved', 'success'],
  circleCheckFull: ['validation', 'verified', 'approved', 'success'],
  circleInfo: ['details', 'tooltip'],
  circleInfoFull: ['details', 'tooltip'],
  circleQuestion: ['help', 'support', 'faq', 'tooltip', '?'],
  circleQuestionFull: ['help', 'support', 'faq', 'tooltip', '?'],
  circleThreeNodes: [],
  circleUser: ['account', 'profile', 'person', 'avatar'],
  circleXmark: ['clear', 'times', 'error'],
  circleXmarkFull: ['clear', 'times', 'error'],
  clockTimeFour: [],
  clockTimeNine: [],
  clockTimeSix: [],
  clockTimeThree: [],
  clockTimeTwelve: ['noon', 'midnight'],
  cloud: [],
  cloudCheck: ['validation', 'verified', 'approved', 'success'],
  cloudDownload: [],
  cloudLock: ['security', 'encryption'],
  cloudUpload: ['save', 'send', 'transfer'],
  cloudXmark: ['clear', 'times'],
  cog: ['gear', 'settings', 'preferences'],
  columns: ['filter', 'grid', 'layout', 'table'],
  comment: ['chat', 'message', 'contact', 'feedback'],
  cpu: ['processor', 'performance', 'hardware'],
  creditCard: ['pay', 'payment', 'transaction'],
  crown: ['premium', 'popular', 'best', 'top', 'vip'],
  dPad: ['controller', 'gamepad', 'gaming'],
  diagnostic: ['health-check'],
  diamondExclamation: ['error', 'urgent', 'alert', '!'],
  diamondExclamationFull: ['error', 'urgent', 'alert', '!'],
  diamondsFull: [],
  discord: ['logo', 'media', 'social'],
  disk: ['drive', 'storage', 'hardware', 'files', 'data'],
  download: [],
  dragDrop: [],
  ellipsisHorizontal: ['truncated'],
  ellipsisVertical: ['more', 'menu', 'options', 'actions'],
  email: ['message', 'contact', 'inbox'],
  emoticon: ['smiley', 'emoji'],
  emoticonDizzy: ['smiley', 'emoji', 'shocked'],
  emoticonNeutral: ['smiley', 'emoji'],
  emoticonSad: ['smiley', 'emoji'],
  emoticonSmile: ['smiley', 'emoji', 'happy'],
  emoticonWink: ['smiley', 'emoji'],
  equal: ['maths'],
  externalLink: [],
  eye: ['see', 'view', 'show', 'visibility', 'masked'],
  eyeOff: ['hide', 'visibility', 'masked'],
  facebook: ['logo', 'media', 'social'],
  fiber: ['network', 'connection'],
  file: ['document', 'paper'],
  fileCopy: ['document', 'duplicate'],
  fileMinus: ['document', 'remove', 'delete'],
  filePlus: ['document', 'add', 'create', 'new'],
  filter: ['sort'],
  flame: ['fire', 'hot', 'popular'],
  flaskEmpty: ['lab', 'test'],
  flaskFull: ['lab', 'test'],
  flaskHalf: ['lab', 'test'],
  floppy: ['save', 'disk', 'storage'],
  focus: [],
  folder: ['directory'],
  folderMinus: ['directory', 'remove', 'delete'],
  folderPlus: ['directory', 'add', 'create', 'new'],
  funnel: ['filter', 'sort'],
  gameConsole: [],
  gameController: [],
  gameControllerAlt: [],
  gathering: ['group'],
  gift: ['reward', 'bonus'],
  github: ['code', 'logo', 'social'],
  globe: ['world', 'global', 'internet'],
  grid: ['apps', 'layout'],
  gridAlt: ['apps', 'layout'],
  hamburgerMenu: ['navigation', 'sidebar'],
  handshake: ['agreement', 'collaboration', 'deal', 'partnership'],
  headphones: ['audio', 'call', 'helpdesk', 'support'],
  heart: ['wishlist', 'love', 'favorite'],
  heartFull: ['wishlist', 'love', 'favorite'],
  heartHalf: ['wishlist', 'love', 'favorite'],
  hexagonExclamation: ['error', 'urgent', 'alert', '!'],
  hexagonExclamationFull: ['error', 'urgent', 'alert', '!'],
  hierarchy: ['tree', 'structure', 'organization'],
  history: ['rollback', 'logs', 'timeline'],
  home: ['house', 'main', 'dashboard'],
  key: ['lock', 'unlock', 'security'],
  keyboard: ['typing'],
  leaf: ['nature', 'green', 'eco', 'carbon'],
  lifeBuoy: ['help', 'support'],
  lightbulb: ['idea'],
  lightning: ['fast', 'flash'],
  linkedin: ['logo', 'media', 'social'],
  list: ['bullet', 'points', 'items'],
  location: ['map', 'place', 'pin'],
  lockClose: ['security', 'access', 'restricted'],
  lockOpen: ['security', 'access', 'unlocked'],
  magicWand: ['wizard', 'fix'],
  magnifyingGlass: ['search', 'zoom', 'find'],
  meter: ['dashboard', 'gauge', 'measure'],
  mic: ['unmute'],
  micOff: ['mute'],
  minus: ['decrease', 'maths', 'less', 'subtract'],
  money: ['cash', 'currency'],
  moneyBagDefault: ['cash', 'wallet'],
  moneyBagDollar: ['cash', 'wallet', '$'],
  moneyBagEuro: ['cash', 'wallet', '€'],
  monitor: ['display', 'screen', 'desktop'],
  moon: ['dark', 'night', 'theme'],
  network: ['snowflake'],
  paperclip: ['attach', 'file', 'document'],
  pause: ['wait', 'hold'],
  pauseFull: ['wait', 'hold'],
  pen: ['edit', 'write', 'modify'],
  percent: ['discount, savings'],
  phone: ['call', 'contact', 'hotline'],
  piggyBank: ['savings', 'economy', 'money', 'budget'],
  pin: [],
  pinOff: [],
  play: ['triangle', 'start', 'begin'],
  playFull: ['triangle', 'start', 'begin'],
  plus: ['add', 'create', 'maths', 'more', 'new'],
  printer: [],
  question: ['help', 'support', '?'],
  reddit: ['logo', 'media', 'social'],
  refresh: ['reload', 'update'],
  resize: ['expand', 'scale'],
  robot: ['chat', 'agent', 'automation'],
  server: ['rack', 'datacenter', 'database'],
  serverRack: ['datacenter', 'database'],
  shareNodes: ['send', 'forward'],
  shareScreen: [],
  shield: ['protection', 'security', 'safe'],
  shieldCheck: ['validation', 'protection', 'security', 'safe', 'verified', 'approved'],
  shieldExclamation: ['protection', 'security', 'safe', 'warning', 'alert'],
  shieldFirewall: ['protection', 'security', 'safe', 'network'],
  shieldLock: ['protection', 'security', 'safe', 'access', 'restricted'],
  shieldMinus: ['protection', 'security', 'safe'],
  shieldOff: ['protection', 'security', 'safe', 'disabled', 'unprotected'],
  shieldPlus: ['protection', 'security', 'safe', 'add'],
  shieldXmark: ['clear', 'times'],
  shoppingCart: ['basket'],
  shoppingCartError: ['basket', 'disabled', 'issue'],
  shoppingCartMinus: ['basket', 'less', 'decrease'],
  shoppingCartPlus: ['basket', 'add', 'more'],
  shoppingCartXmark: ['basket', 'clear', 'remove','times'],
  shrink: ['reduce', 'minimize', 'scale'],
  shutdown: ['off', 'logout', 'power'],
  snowflake: [],
  sortAlphaDown: ['ascending', 'order'],
  sortAlphaUp: ['descending', 'order'],
  sortNumericDown: ['descending', 'order'],
  sortNumericUp: ['ascending', 'order'],
  sparkle: ['ai', 'shine', 'special'],
  splitHorizontal: ['screen'],
  splitVertical: ['screen'],
  sslKey: ['security'],
  star: ['favorite', 'rating', 'bookmark'],
  starFull: ['favorite', 'rating', 'bookmark'],
  starHalf: ['favorite', 'rating', 'bookmark'],
  stop: ['square', 'end'],
  stopFull: ['square', 'end'],
  store: ['shop', 'marketplace', 'retail'],
  suitcase: ['business', 'travel', 'work'],
  sun: ['day', 'light', 'theme'],
  sync: ['portability', 'update', 'refresh', 'reload'],
  tag: ['label', 'promotion'],
  target: ['goal', 'objective'],
  theme: ['dark', 'light', 'mode'],
  thumbsDown: ['like'],
  thumbsUp: ['like'],
  timer: ['alarm', 'clock', 'countdown'],
  trafficCone: ['wip', 'construction'],
  trash: ['bin', 'delete', 'remove'],
  triangleExclamation: ['warning', 'alert', '!'],
  triangleExclamationFull: ['warning', 'alert', '!'],
  triangleThreeNodes: [],
  truck: ['shipping', 'shipment', 'delivery', 'transport', 'vehicle'],
  twitch: ['game', 'logo', 'media', 'social', 'stream'],
  undo: ['reverse'],
  upload: ['send', 'transfer'],
  user: ['account', 'profile', 'person'],
  userFull: [],
  vault: ['protection', 'security', 'safe'],
  x: ['logo', 'media', 'social', 'twitter'],
  xmark: ['cancel', 'clear', 'close', 'delete', 'maths', 'multiply', 'times'],
  youtube: ['logo', 'media', 'social', 'video'],
};

export {
  type IconNameKey,
  ODS_ICON_TAG,
};
