// Since v7, storybook does not allow anything else than string literal on Meta.
// so we can't use those constants on meta declaration and still needs to duplicate those values.
// Until a solution is found, those are still useful when defining <StorybookLink />

enum SECTION {
  build = 'Build',
  customize = 'Customize',
  home = 'OVHcloud Design System',
  previousMigrations = 'Previous Migrations',
  reactComponents = 'React Components',
  recipes = 'Recipes',
  resources = 'Resources',
  tools = 'Tools',
  upgrade = 'Upgrade',
}

enum HOME_TITLE {
  accessibilityGuide = `${SECTION.home}/${SECTION.build}/Accessibility`,
  applyOdsStyle = `${SECTION.home}/${SECTION.customize}/Apply ODS Style`,
  changelog = `${SECTION.home}/${SECTION.upgrade}/Changelog`,
  charts = `${SECTION.home}/${SECTION.build}/Charts`,
  designTokens = `${SECTION.home}/${SECTION.customize}/Design Tokens`,
  faq = `${SECTION.home}/${SECTION.resources}/F.A.Q.`,
  formGuidelines = `${SECTION.home}/${SECTION.build}/Forms`,
  getStarted = `${SECTION.home}/Get Started`,
  i18nGuide = `${SECTION.home}/${SECTION.build}/Internationalization`,
  implementingFormGuide = `${SECTION.home}/${SECTION.build}/Forms`,
  llmDocs = `${SECTION.home}/${SECTION.resources}/LLM Documentation`,
  migration12to13 = `${SECTION.home}/${SECTION.upgrade}/${SECTION.previousMigrations}/12.x to 13.x`,
  migration13to14 = `${SECTION.home}/${SECTION.upgrade}/${SECTION.previousMigrations}/13.x to 14.x`,
  migration14to15 = `${SECTION.home}/${SECTION.upgrade}/${SECTION.previousMigrations}/14.x to 15.x`,
  migration15to16 = `${SECTION.home}/${SECTION.upgrade}/${SECTION.previousMigrations}/15.x to 16.x`,
  migration16to17 = `${SECTION.home}/${SECTION.upgrade}/${SECTION.previousMigrations}/16.x to 17.x`,
  migration17to18 = `${SECTION.home}/${SECTION.upgrade}/${SECTION.previousMigrations}/17.x to 18.x`,
  migrationToV19 = `${SECTION.home}/${SECTION.upgrade}/Migration to v19`,
  roadmap = `${SECTION.home}/${SECTION.resources}/Roadmap`,
  sandboxTool = `${SECTION.home}/${SECTION.tools}/Code Sandbox`,
  styleCustomization = `${SECTION.home}/${SECTION.customize}/Style Customization`,
  tailwind = `${SECTION.home}/${SECTION.customize}/Tailwind CSS Integration`,
  themeGenerator = `${SECTION.home}/${SECTION.tools}/Theme Generator`,
  welcome = `${SECTION.home}/Welcome`,
  whatsnew = `${SECTION.home}/${SECTION.upgrade}/What's new`,
}

enum REACT_COMPONENTS_TITLE {
  gallery = `${SECTION.reactComponents}/Gallery`,
  accordion = `${SECTION.reactComponents}/Accordion`,
  avatar = `${SECTION.reactComponents}/Avatar`,
  badge = `${SECTION.reactComponents}/Badge`,
  breadcrumb = `${SECTION.reactComponents}/Breadcrumb`,
  button = `${SECTION.reactComponents}/Button`,
  buttonGroup = `${SECTION.reactComponents}/Button Group`,
  card = `${SECTION.reactComponents}/Card`,
  cart = `${SECTION.reactComponents}/Cart`,
  checkbox = `${SECTION.reactComponents}/Checkbox`,
  clipboard = `${SECTION.reactComponents}/Clipboard`,
  code = `${SECTION.reactComponents}/Code`,
  combobox = `${SECTION.reactComponents}/Combobox`,
  contentAddon = `${SECTION.reactComponents}/Content Addon`,
  dataTable = `${SECTION.reactComponents}/Data Table`,
  datepicker = `${SECTION.reactComponents}/Datepicker`,
  divider = `${SECTION.reactComponents}/Divider`,
  drawer = `${SECTION.reactComponents}/Drawer`,
  editable = `${SECTION.reactComponents}/Editable`,
  fileThumbnail = `${SECTION.reactComponents}/File Thumbnail`,
  fileUpload = `${SECTION.reactComponents}/File Upload`,
  flag = `${SECTION.reactComponents}/Flag`,
  formField = `${SECTION.reactComponents}/Form Field`,
  icon = `${SECTION.reactComponents}/Icon`,
  input = `${SECTION.reactComponents}/Input`,
  kbd = `${SECTION.reactComponents}/Kbd`,
  link = `${SECTION.reactComponents}/Link`,
  logo = `${SECTION.reactComponents}/Logo`,
  markdown = `${SECTION.reactComponents}/Markdown`,
  medium = `${SECTION.reactComponents}/Medium`,
  menu = `${SECTION.reactComponents}/Menu`,
  message = `${SECTION.reactComponents}/Message`,
  messageBubble = `${SECTION.reactComponents}/Message Bubble`,
  meter = `${SECTION.reactComponents}/Meter`,
  modal = `${SECTION.reactComponents}/Modal`,
  pagination = `${SECTION.reactComponents}/Pagination`,
  password = `${SECTION.reactComponents}/Password`,
  phoneNumber = `${SECTION.reactComponents}/Phone Number`,
  popover = `${SECTION.reactComponents}/Popover`,
  progressBar = `${SECTION.reactComponents}/Progress Bar`,
  promptInput = `${SECTION.reactComponents}/Prompt Input`,
  searchBar = `${SECTION.reactComponents}/Search Bar`,
  quantity = `${SECTION.reactComponents}/Quantity`,
  queryFilter = `${SECTION.reactComponents}/Query Filter`,
  radioGroup = `${SECTION.reactComponents}/Radio Group`,
  range = `${SECTION.reactComponents}/Range`,
  select = `${SECTION.reactComponents}/Select`,
  skeleton = `${SECTION.reactComponents}/Skeleton`,
  spinner = `${SECTION.reactComponents}/Spinner`,
  switch = `${SECTION.reactComponents}/Switch`,
  table = `${SECTION.reactComponents}/Table`,
  tabs = `${SECTION.reactComponents}/Tabs`,
  tag = `${SECTION.reactComponents}/Tag`,
  text = `${SECTION.reactComponents}/Text`,
  textarea = `${SECTION.reactComponents}/Textarea`,
  tile = `${SECTION.reactComponents}/Tile`,
  timepicker = `${SECTION.reactComponents}/Timepicker`,
  toaster = `${SECTION.reactComponents}/Toaster`,
  toggle = `${SECTION.reactComponents}/Toggle`,
  tooltip = `${SECTION.reactComponents}/Tooltip`,
  treeView = `${SECTION.reactComponents}/Tree View`,
}

enum RECIPES_TITLE {
  components = `${SECTION.recipes}/Components`,
}

enum STORY {
  documentation = 'Documentation',
  technicalInformation = 'Technical information',
}

export {
  HOME_TITLE,
  REACT_COMPONENTS_TITLE,
  RECIPES_TITLE,
  SECTION,
  STORY,
};
