export const OcdkSurfaceBasicPositionList: string[] = [
  'TOP_LEFT TOP_RIGHT',
  'TOP_RIGHT TOP_LEFT',
  'BOTTOM_LEFT BOTTOM_RIGHT',
  'BOTTOM_RIGHT BOTTOM_LEFT',
  'BOTTOM_LEFT TOP_LEFT',
  'TOP_LEFT BOTTOM_LEFT',
  'BOTTOM_RIGHT TOP_RIGHT',
  'TOP_RIGHT BOTTOM_RIGHT',
  'BOTTOM_CENTER TOP_CENTER',
  'TOP_CENTER BOTTOM_CENTER',
];
