packages:
  - "packages/examples/*"
  - "packages/ods-react"
  - "packages/ods-react/src/components/*"
  - "packages/ods-recipes"
  - "packages/ods-recipes/src/components/*"
  - "packages/storybook"
  - "packages/themes"

overrides:
  "@types/scheduler": "< 0.23.0"
  "@types/react": "^18.0.0"

patchedDependencies:
  '@fluentui/storybook-llms-extractor@0.0.3': patches/@fluentui__storybook-llms-extractor@0.0.3.patch
