graph TB

    subgraph THEME CONFIG
        tsizes(ThemeTypography)-- Each level like *title* <br/>is configured for the different size properties --> themeTypoProp((typo properties))
        themeTypoProp((typo properties))-- Each size property like *font-size*<br/>is set with value --> value{CSS property}

    end

    subgraph THEMING SYSTEM
        sdef(TypographyDefinitions)-- Each level like *title* <br/>is defined in different typo properties --> prop((typo properties))
        prop((typo properties))-- Each typo property like *font-size*<br/>is a CSS variables --> var{CSS variables}
    end

    classDef green fill:#9f6,stroke:#333,stroke-width:2px;
    classDef blue fill:#16C2E5,stroke:#333,stroke-width:2px;
    class var,value green
    class prop,themeTypoProp blue
