import { ODS_THEME_COLOR_INTENT, ODS_THEME_COLOR_INTENTS, ODS_THEME_COLOR_HUE, ODS_THEME_COLOR_HUES } from '@ovhcloud/ods-common-theming';

export {
  ODS_THEME_COLOR_INTENT as ODS_TEXT_COLOR_INTENT,
  ODS_THEME_COLOR_HUE as ODS_TEXT_COLOR_HUE,
  ODS_THEME_COLOR_INTENTS as ODS_TEXT_COLOR_INTENTS,
  ODS_THEME_COLOR_HUES as ODS_TEXT_COLOR_HUES,
};
