const data = [
    { author: 'Guillaume Meurice', title: 'Le roi n\'avait pas ri', price: '6€'},
    { author: 'Maupassant', title: 'Bel ami', price: '9€'},
    { author: 'Maupassant', title: 'Le horla', price: '15€'},
    { author: 'Gustave Flaubert', title: 'Madame de bovary', price: '12€'},
    { author: 'Émile Zola', title: 'Germinal', price: '5€'},
    { author: 'Guillaume Meurice', title: 'Le roi n\'avait pas ri', price: '6€'},
    { author: 'Maupassant', title: 'Bel ami', price: '9€'},
    { author: 'Maupassant', title: 'Le horla', price: '15€'},
    { author: 'Gustave Flaubert', title: 'Madame de bovary', price: '12€'},
    { author: 'Émile Zola', title: 'Germinal', price: '5€'},  { author: 'Guillaume Meurice', title: 'Le roi n\'avait pas ri', price: '6€'},
    { author: 'Maupassant', title: 'Bel ami', price: '9€'},
    { author: 'Maupassant', title: 'Le horla', price: '15€'},
    { author: 'Gustave Flaubert', title: 'Madame de bovary', price: '12€'},
    { author: 'Émile Zola', title: 'Germinal', price: '5€'},  { author: 'Guillaume Meurice', title: 'Le roi n\'avait pas ri', price: '6€'},
    { author: 'Maupassant', title: 'Bel ami', price: '9€'},
    { author: 'Maupassant', title: 'Le horla', price: '15€'},
    { author: 'Gustave Flaubert', title: 'Madame de bovary', price: '12€'},
    { author: 'Émile Zola', title: 'Germinal', price: '5€'},  { author: 'Guillaume Meurice', title: 'Le roi n\'avait pas ri', price: '6€'},
    { author: 'Maupassant', title: 'Bel ami', price: '9€'},
    { author: 'Maupassant', title: 'Le horla', price: '15€'},
    { author: 'Gustave Flaubert', title: 'Madame de bovary', price: '12€'},
    { author: 'Émile Zola', title: 'Germinal', price: '5€'},  { author: 'Guillaume Meurice', title: 'Le roi n\'avait pas ri', price: '6€'},
    { author: 'Maupassant', title: 'Bel ami', price: '9€'},
    { author: 'Maupassant', title: 'Le horla', price: '15€'},
    { author: 'Gustave Flaubert', title: 'Madame de bovary', price: '12€'},
    { author: 'Émile Zola', title: 'Germinal', price: '5€'},  { author: 'Guillaume Meurice', title: 'Le roi n\'avait pas ri', price: '6€'},
    { author: 'Maupassant', title: 'Bel ami', price: '9€'},
    { author: 'Maupassant', title: 'Le horla', price: '15€'},
    { author: 'Gustave Flaubert', title: 'Madame de bovary', price: '12€'},
    { author: 'Émile Zola', title: 'Germinal', price: '5€'},  { author: 'Guillaume Meurice', title: 'Le roi n\'avait pas ri', price: '6€'},
    { author: 'Maupassant', title: 'Bel ami', price: '9€'},
    { author: 'Maupassant', title: 'Le horla', price: '15€'},
    { author: 'Gustave Flaubert', title: 'Madame de bovary', price: '12€'},
    { author: 'Émile Zola', title: 'Germinal', price: '5€'},  { author: 'Guillaume Meurice', title: 'Le roi n\'avait pas ri', price: '6€'},
    { author: 'Maupassant', title: 'Bel ami', price: '9€'},
    { author: 'Maupassant', title: 'Le horla', price: '15€'},
    { author: 'Gustave Flaubert', title: 'Madame de bovary', price: '12€'},
    { author: 'Émile Zola', title: 'Germinal', price: '5€'},  { author: 'Guillaume Meurice', title: 'Le roi n\'avait pas ri', price: '6€'},
    { author: 'Maupassant', title: 'Bel ami', price: '9€'},
    { author: 'Maupassant', title: 'Le horla', price: '15€'},
    { author: 'Gustave Flaubert', title: 'Madame de bovary', price: '12€'},
    { author: 'Émile Zola', title: 'Germinal', price: '5€'},  { author: 'Guillaume Meurice', title: 'Le roi n\'avait pas ri', price: '6€'},
    { author: 'Maupassant', title: 'Bel ami', price: '9€'},
    { author: 'Maupassant', title: 'Le horla', price: '15€'},
    { author: 'Gustave Flaubert', title: 'Madame de bovary', price: '12€'},
    { author: 'Émile Zola', title: 'Germinal', price: '5€'},
    { author: 'Stendhal', title: 'Germinal', price: '20€',
    serviceHistory:[
        {date:"22/05/2017", engineer:"Jimmy Brown", actions:"Aligned wheels"},
        {date:"11/02/2018", engineer:"Lotty Ferberson", actions:"Changed Oil"},
        {date:"04/04/2018", engineer:"Franco Martinez", actions:"Fixed Tracking"},
    ]},
];

export { 
    data,
}