const ODS_PAGINATION_PER_PAGE_MIN = 10;
const ODS_PAGINATION_PER_PAGE_MAX = 300;
const ODS_PAGINATION_PER_PAGE_OPTIONS = Object.freeze([ODS_PAGINATION_PER_PAGE_MIN, 25, 50, 100, ODS_PAGINATION_PER_PAGE_MAX]);

export {
  ODS_PAGINATION_PER_PAGE_MAX,
  ODS_PAGINATION_PER_PAGE_MIN,
  ODS_PAGINATION_PER_PAGE_OPTIONS,
};
