graph TB

    subgraph THEME CONFIG
        tpalette(ThemePalettes)-- Each palette like *blue* <br/>is defined with different hue --> themeHues((Hues))
        themeHues((Hues))-- Each hue like *blue-500*<br/>is an hsla color --> hslacolor{hsla color}
        ci(ThemeColorIntents)-- Each color intent like *primary*<br/>corresponds to a palette name like *blue* -.-> colorName((PaletteName))

    end

    subgraph THEMING SYSTEM
        pdef(PaletteDefinitions)-- Each palette like *blue* <br/>is defined with different hue --> hues((Hues))
        hues((Hues))-- Each color hue like *blue-500*<br/>is a CSS variables --> var{CSS variables}
    end

    classDef green fill:#9f6,stroke:#333,stroke-width:2px;
    classDef blue fill:#16C2E5,stroke:#333,stroke-width:2px;
    class var,hslacolor green
    class hues,themeHues blue
