#!/usr/bin/env node
// Gathers the documentation content bundled into the published package:
//   content/llms/        ← packages/docs/assets/llms (committed, verified set)
//   content/tokens.json  ← packages/themes/dist (built on demand)
//   content/recipes.json ← packages/ods-recipes/dist (built on demand)
//   content/icons.json   ← icon names (ods-react enum) + search aliases (docs)
import { execSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = resolve(PKG, '../..');
const OUT = resolve(PKG, 'content');
mkdirSync(OUT, { recursive: true });

// 1. llms set (committed in the repo, no build required)
const LLMS = resolve(ROOT, 'packages/docs/assets/llms');
if (!existsSync(resolve(LLMS, 'llms-index.json'))) {
  console.error('✗ packages/docs/assets/llms missing — corrupted checkout?');
  process.exit(1);
}
cpSync(LLMS, resolve(OUT, 'llms'), { recursive: true });

// 2. workspace dists the next steps depend on (recipes' build needs ods-react)
if (!existsSync(resolve(ROOT, 'packages/ods-react/dist/index.js'))) {
  console.log('▶ ods-react dist missing — building @ovhcloud/ods-react…');
  execSync('pnpm --filter @ovhcloud/ods-react run build:prod', { cwd: ROOT, stdio: 'inherit' });
}

// 3. theme tokens (generated by the themes build)
const TOKENS = resolve(ROOT, 'packages/themes/dist/default/tokens.json');
if (!existsSync(TOKENS)) {
  console.log('▶ themes dist missing — building @ovhcloud/ods-themes…');
  execSync('pnpm --filter @ovhcloud/ods-themes run build:prod', { cwd: ROOT, stdio: 'inherit' });
}
cpSync(TOKENS, resolve(OUT, 'tokens.json'));

// 4. recipes metadata + sources (generated by the recipes build)
const RECIPES = resolve(ROOT, 'packages/ods-recipes/dist/ods-recipes.json');
if (!existsSync(RECIPES)) {
  console.log('▶ recipes dist missing — building @ovhcloud/ods-recipes…');
  execSync('pnpm --filter @ovhcloud/ods-recipes run build:prod', { cwd: ROOT, stdio: 'inherit' });
}
cpSync(RECIPES, resolve(OUT, 'recipes.json'));

// 5. icons: names from the ods-react enum, search aliases from the docs constants.
const enumSrc = readFileSync(resolve(ROOT, 'packages/ods-react/src/components/icon/src/constants/icon-name.ts'), 'utf8');
const names = {};
for (const [, key, value] of enumSrc.matchAll(/^\s{2}(\w+) = '([^']+)',?$/gm)) {
  names[key] = value;
}

const tagsSrc = readFileSync(resolve(ROOT, 'packages/docs/src/doc/ports/constants/iconTags.ts'), 'utf8');
// The declaration is `const ODS_ICON_TAG: <type> = { … }`: the object literal
// starts at the first brace AFTER the `=`, not after the (mapped-type) annotation.
const eq = tagsSrc.indexOf('=', tagsSrc.indexOf('const ODS_ICON_TAG'));
const start = tagsSrc.indexOf('{', eq);
let depth = 0, end = start;
for (let i = start; i < tagsSrc.length; i += 1) {
  const c = tagsSrc[i];
  if (c === '{') depth += 1;
  if (c === '}') { depth -= 1; if (depth === 0) { end = i + 1; break; } }
}
const tags = (await import(`data:text/javascript,${encodeURIComponent(`export default ${tagsSrc.slice(start, end)}`)}`)).default;

const icons = Object.entries(names).map(([key, name]) => ({ name, tags: tags[key] ?? [] }));
writeFileSync(resolve(OUT, 'icons.json'), JSON.stringify(icons));

console.log(`✓ content bundled: llms set, tokens, recipes, ${icons.length} icons`);
