#!/usr/bin/env node
// Gathers the documentation content bundled into the published package:
//   content/llms/        ← packages/docs/assets/llms (committed, verified set):
//                          llms-index.json + the pages it references, nothing else
//   content/tokens.json  ← packages/themes/dist (rebuilt when missing or stale)
//   content/recipes.json ← packages/ods-recipes/dist (rebuilt when missing or stale)
//   content/icons.json   ← icon names (ods-react enum) + search aliases (docs)
import { execSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = resolve(PKG, '../..');
const OUT = resolve(PKG, 'content');
mkdirSync(OUT, { recursive: true });

// Freshness: a workspace dist is reused only if it is newer than every file of
// its inputs (mtime). Simpler than always rebuilding (ods-react takes minutes)
// and safe: a checkout or an edit touches the sources (a deletion touches its
// directory, hence directories count too), which forces a rebuild;
// at worst a no-op touch rebuilds for nothing, never ships a stale dist.
function newestMtime(path) {
  if (!existsSync(path)) {
    return 0;
  }
  const stat = statSync(path);
  if (!stat.isDirectory()) {
    return stat.mtimeMs;
  }
  let newest = stat.mtimeMs;
  for (const entry of readdirSync(path)) {
    if (entry !== 'node_modules' && entry !== 'dist') {
      newest = Math.max(newest, newestMtime(resolve(path, entry)));
    }
  }
  return newest;
}

function isFresh(artifact, inputs) {
  return existsSync(artifact)
    && statSync(artifact).mtimeMs >= Math.max(...inputs.map((input) => newestMtime(input)));
}

function ensureBuilt(name, dir, artifact, inputs, before = () => {}) {
  const target = resolve(ROOT, dir, artifact);
  if (isFresh(target, inputs.map((input) => resolve(ROOT, dir, input)))) {
    return target;
  }
  console.log(`▶ ${relative(ROOT, target)} ${existsSync(target) ? 'older than its sources' : 'missing'} — building ${name}…`);
  before();
  execSync(`pnpm --filter ${name} run build:prod`, { cwd: ROOT, stdio: 'inherit' });
  if (!existsSync(target)) {
    throw new Error(`copy-content: ${name} build did not produce ${relative(ROOT, target)}`);
  }
  return target;
}

// 1. llms set (committed in the repo, no build required). Only the index and the
//    pages it references are shipped: the aggregated files (llms-full.txt, the
//    ods-documentation-*/ods-*-index files, llms.txt) are never read by the server.
const LLMS = resolve(ROOT, 'packages/docs/assets/llms');
const INDEX = resolve(LLMS, 'llms-index.json');
if (!existsSync(INDEX)) {
  console.error('✗ packages/docs/assets/llms missing — corrupted checkout?');
  process.exit(1);
}
const llmsIndex = JSON.parse(readFileSync(INDEX, 'utf8'));
const pages = new Set([
  ...llmsIndex.components.flatMap((c) => Object.values(c.pages).map((p) => p.url)),
  ...llmsIndex.generic.map((g) => g.url),
].map((url) => url.replace(/^\.\//, '')));
mkdirSync(resolve(OUT, 'llms'), { recursive: true });
copyFileSync(INDEX, resolve(OUT, 'llms', 'llms-index.json'));
for (const page of pages) {
  const from = resolve(LLMS, page);
  if (!existsSync(from)) {
    throw new Error(`copy-content: llms-index.json references ${page}, missing from packages/docs/assets/llms`);
  }
  copyFileSync(from, resolve(OUT, 'llms', page));
}

// 2. theme tokens (generated by the themes build)
const TOKENS = ensureBuilt('@ovhcloud/ods-themes', 'packages/themes', 'dist/default/tokens.json', ['src', 'scripts']);
copyFileSync(TOKENS, resolve(OUT, 'tokens.json'));

// 3. recipes metadata + sources (generated by the recipes build). The recipes
//    build compiles against ods-react's dist: only when recipes must actually be
//    rebuilt is ods-react itself checked (and rebuilt if missing or stale).
const RECIPES = ensureBuilt('@ovhcloud/ods-recipes', 'packages/ods-recipes', 'dist/ods-recipes.json', ['src', 'scripts'], () => {
  ensureBuilt('@ovhcloud/ods-react', 'packages/ods-react', 'dist/index.js', ['src']);
});
copyFileSync(RECIPES, resolve(OUT, 'recipes.json'));

// 4. icons: names from the ods-react enum, search aliases from the docs constants.
const enumSrc = readFileSync(resolve(ROOT, 'packages/ods-react/src/components/icon/src/constants/icon-name.ts'), 'utf8');
const names = {};
// Assumes the enum's current shape (2-space indent, single-quoted values); a
// reformat yields zero matches, so fail the build loudly rather than ship an
// empty icon list.
for (const [, key, value] of enumSrc.matchAll(/^\s{2}(\w+) = '([^']+)',?$/gm)) {
  names[key] = value;
}
if (Object.keys(names).length === 0) {
  throw new Error('copy-content: no icon extracted from icon-name.ts — the enum format changed');
}

const tagsSrc = readFileSync(resolve(ROOT, 'packages/docs/src/doc/ports/constants/iconTags.ts'), 'utf8');
// The declaration is `const ODS_ICON_TAG: <type> = { … }`: the object literal
// starts at the first brace AFTER the `=`, not after the (mapped-type) annotation.
// Same policy as the enum: a renamed or reshaped declaration fails the build.
const decl = tagsSrc.indexOf('const ODS_ICON_TAG');
const eq = decl === -1 ? -1 : tagsSrc.indexOf('=', decl);
const start = eq === -1 ? -1 : tagsSrc.indexOf('{', eq);
if (start === -1) {
  throw new Error('copy-content: `const ODS_ICON_TAG … = {` not found in iconTags.ts — the declaration changed');
}
let depth = 0, end = -1;
for (let i = start; i < tagsSrc.length; i += 1) {
  const c = tagsSrc[i];
  if (c === '{') depth += 1;
  if (c === '}') { depth -= 1; if (depth === 0) { end = i + 1; break; } }
}
if (end === -1) {
  throw new Error('copy-content: unbalanced braces in the ODS_ICON_TAG object literal');
}
const tags = (await import(`data:text/javascript,${encodeURIComponent(`export default ${tagsSrc.slice(start, end)}`)}`)).default;

const icons = Object.entries(names).map(([key, name]) => ({ name, tags: tags[key] ?? [] }));
writeFileSync(resolve(OUT, 'icons.json'), JSON.stringify(icons));

console.log(`✓ content bundled: ${pages.size} llms pages + index, tokens, recipes, ${icons.length} icons`);
