#!/usr/bin/env bash
#
# Public API non-regression snapshot for @ovhcloud/ods-react.
#
# Deterministically concatenates every .d.ts emitted in dist/src into a single
# versioned reference file. Each run regenerates and compares: any change to the
# public type contract (prop, signature, exported type…) shows up in the diff —
# that is the "this bump touches the public API (semver)" signal.
#
# Robust against the polymorphic "dangling T" bug that crashes api-extractor.
#
# Usage:
#   bash scripts/api-snapshot.sh             # check (fails if the API changed)
#   bash scripts/api-snapshot.sh --update    # regenerate the reference after a wanted change
#   bash scripts/api-snapshot.sh --no-build  # check against the existing dist (faster, may be stale)
#
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PKG="$ROOT/packages/ods-react"
DIST_TYPES="$PKG/dist/src"
REF="$PKG/etc/public-api.api.txt"
MODE="${1:-check}"

# Rebuild by default: a stale dist silently produces a false pass/fail, so the
# snapshot must always be derived from the current sources. --no-build opts out.
if [ "$MODE" = "--no-build" ]; then
  MODE="check"
  if [ ! -d "$DIST_TYPES" ]; then
    echo "✗ --no-build requested but $DIST_TYPES is missing"; exit 1
  fi
else
  echo "▶ building @ovhcloud/ods-react (snapshot must reflect current sources)…"
  pnpm --filter @ovhcloud/ods-react run build:prod > /dev/null || { echo "✗ ods-react build failed"; exit 1; }
fi

# Generate the current snapshot (stable order, relative paths)
CURRENT="$(mktemp)"
{
  echo "// Public API snapshot of @ovhcloud/ods-react — generated by scripts/api-snapshot.sh"
  echo "// Do not edit by hand. Regenerate with: bash scripts/api-snapshot.sh --update"
  echo ""
  while IFS= read -r f; do
    rel="${f#"$DIST_TYPES"/}"
    echo "// ==================== $rel ===================="
    cat "$f"
    echo ""
  done < <(cd "$DIST_TYPES" && find . -name '*.d.ts' | LC_ALL=C sort | sed "s#^\./#$DIST_TYPES/#")
} > "$CURRENT"

mkdir -p "$PKG/etc"

if [ "$MODE" = "--update" ] || [ "$MODE" = "update" ]; then
  mv "$CURRENT" "$REF"
  echo "✓ API reference updated: ${REF#"$ROOT"/}"
  exit 0
fi

if [ ! -f "$REF" ]; then
  mv "$CURRENT" "$REF"
  echo "✓ API reference created (baseline): ${REF#"$ROOT"/}"
  echo "  Commit this file; subsequent runs will compare against it."
  exit 0
fi

DIFF_FILE="$(mktemp -t api-snapshot-diff)"
if diff -u "$REF" "$CURRENT" > "$DIFF_FILE" 2>&1; then
  rm -f "$CURRENT" "$DIFF_FILE"
  echo "✓ Public API unchanged."
  exit 0
else
  echo "✗ The public API CHANGED — review required (possible semver impact):"
  echo "-----------------------------------------------------------------"
  head -80 "$DIFF_FILE"
  echo "-----------------------------------------------------------------"
  echo "Full diff: $DIFF_FILE"
  echo "If the change is intended: bash scripts/api-snapshot.sh --update"
  rm -f "$CURRENT"
  exit 1
fi
